<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Wiretap</PackageId>
    <Version>1.0.0</Version>
    <Authors>HeDev</Authors>
    <Company>HeDev</Company>
    <Description>Contract-based logging extension.</Description>
    <PackageTags>logging;observability;telemetry</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
<!--    <PackageReadmeFile>README.md</PackageReadmeFile>-->
    <RepositoryUrl>https://github.com/he-dev/wiretap-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/he-dev/wiretap-dotnet</PackageProjectUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
